version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    restart: always
    tty: true
    ports:
      - 8098:80
    links:
      - fpm
    volumes:
      - ./:/var/www/tapir-test
    networks:
      - app-network

  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    container_name: app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www/tapir-test
    links:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tapir_test
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
